//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabtBilMusteriKayit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RabtBilMusteriKayit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri kayıtlarını günceller..
        /// </summary>
        internal static string aciklamaBttnGuncelle {
            get {
                return ResourceManager.GetString("aciklamaBttnGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen bilgileri veritabanına kaydeder..
        /// </summary>
        internal static string aciklamaBttnKaydet {
            get {
                return ResourceManager.GetString("aciklamaBttnKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri kayıtlarını gösterir..
        /// </summary>
        internal static string aciklamaBttnKayitlariGoster {
            get {
                return ResourceManager.GetString("aciklamaBttnKayitlariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metin kutularını temizler..
        /// </summary>
        internal static string aciklamaBttnTemizle {
            get {
                return ResourceManager.GetString("aciklamaBttnTemizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni bir kayıt oluşturur..
        /// </summary>
        internal static string aciklamaBttnYeniKayit {
            get {
                return ResourceManager.GetString("aciklamaBttnYeniKayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programın dilini değiştirir..
        /// </summary>
        internal static string aciklamaDil {
            get {
                return ResourceManager.GetString("aciklamaDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kaydı günceller..
        /// </summary>
        internal static string aciklamaGuncelle {
            get {
                return ResourceManager.GetString("aciklamaGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu program hakkında bazı bilgiler..
        /// </summary>
        internal static string aciklamaHakkinda {
            get {
                return ResourceManager.GetString("aciklamaHakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans anahtarınızı etkinleştirin..
        /// </summary>
        internal static string aciklamaLisansAnahtari {
            get {
                return ResourceManager.GetString("aciklamaLisansAnahtari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil resminiz..
        /// </summary>
        internal static string aciklamaPcTrBoxProfiliDuzenle {
            get {
                return ResourceManager.GetString("aciklamaPcTrBoxProfiliDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kaydı siler..
        /// </summary>
        internal static string aciklamaSil {
            get {
                return ResourceManager.GetString("aciklamaSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programın temasını değiştirir..
        /// </summary>
        internal static string aciklamaTema {
            get {
                return ResourceManager.GetString("aciklamaTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen müşterinin kaydını siler..
        /// </summary>
        internal static string aciklamaTlStrpMenuItemAraclarSil {
            get {
                return ResourceManager.GetString("aciklamaTlStrpMenuItemAraclarSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kaydı yazdırır..
        /// </summary>
        internal static string aciklamaYazdir {
            get {
                return ResourceManager.GetString("aciklamaYazdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni bir kayıt ekler..
        /// </summary>
        internal static string aciklamaYeniKayit {
            get {
                return ResourceManager.GetString("aciklamaYeniKayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Pencere.
        /// </summary>
        internal static string BttnAnaPencere {
            get {
                return ResourceManager.GetString("BttnAnaPencere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinleştir.
        /// </summary>
        internal static string BttnEtkinlestir {
            get {
                return ResourceManager.GetString("BttnEtkinlestir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string BttnGirisYap {
            get {
                return ResourceManager.GetString("BttnGirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string BttnKaydet {
            get {
                return ResourceManager.GetString("BttnKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopyala.
        /// </summary>
        internal static string BttnKopyala {
            get {
                return ResourceManager.GetString("BttnKopyala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Kodunu Oluştur.
        /// </summary>
        internal static string BttnQrKoduOlustur {
            get {
                return ResourceManager.GetString("BttnQrKoduOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string BttnSil {
            get {
                return ResourceManager.GetString("BttnSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string BttnTemizle {
            get {
                return ResourceManager.GetString("BttnTemizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazdır.
        /// </summary>
        internal static string BttnYazdir {
            get {
                return ResourceManager.GetString("BttnYazdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kullanıcı Oluştur.
        /// </summary>
        internal static string BttnYeniKullaniciOluştur {
            get {
                return ResourceManager.GetString("BttnYeniKullaniciOluştur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre Gönder.
        /// </summary>
        internal static string BttnYeniKullaniciOluştur2 {
            get {
                return ResourceManager.GetString("BttnYeniKullaniciOluştur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük Harfler.
        /// </summary>
        internal static string ChckBoxBuyukHarfler {
            get {
                return ResourceManager.GetString("ChckBoxBuyukHarfler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçük Harfler.
        /// </summary>
        internal static string ChckBoxKucukHarfler {
            get {
                return ResourceManager.GetString("ChckBoxKucukHarfler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayılar.
        /// </summary>
        internal static string ChckBoxSayilar {
            get {
                return ResourceManager.GetString("ChckBoxSayilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Semboller.
        /// </summary>
        internal static string ChckBoxSemboller {
            get {
                return ResourceManager.GetString("ChckBoxSemboller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        internal static string CmbBoxUrunKodlariDiger {
            get {
                return ResourceManager.GetString("CmbBoxUrunKodlariDiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imei No.
        /// </summary>
        internal static string CmbBoxUrunKodlariImeiNo {
            get {
                return ResourceManager.GetString("CmbBoxUrunKodlariImeiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri No.
        /// </summary>
        internal static string CmbBoxUrunKodlariSeriNo {
            get {
                return ResourceManager.GetString("CmbBoxUrunKodlariSeriNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programın deneme sürümünü kullanıyorsunuz!.
        /// </summary>
        internal static string denemeSurumu {
            get {
                return ResourceManager.GetString("denemeSurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen doğru bir e-posta adresi girin!.
        /// </summary>
        internal static string dogruBirEpostaGirin {
            get {
                return ResourceManager.GetString("dogruBirEpostaGirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir e-posta adresi girin!.
        /// </summary>
        internal static string dogruEpostaGir {
            get {
                return ResourceManager.GetString("dogruEpostaGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresiniz boş olamaz!.
        /// </summary>
        internal static string epostaBos {
            get {
                return ResourceManager.GetString("epostaBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçici Kullanıcı Adınız:.
        /// </summary>
        internal static string epostaGeciciKullaniciAdi {
            get {
                return ResourceManager.GetString("epostaGeciciKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçici Şifreniz:.
        /// </summary>
        internal static string epostaGeciciSifre {
            get {
                return ResourceManager.GetString("epostaGeciciSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir e-posta adresi kayıtlı değil!.
        /// </summary>
        internal static string epostaKayitliDegil {
            get {
                return ResourceManager.GetString("epostaKayitliDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Sıfırlama.
        /// </summary>
        internal static string epostaSifremiUnuttum {
            get {
                return ResourceManager.GetString("epostaSifremiUnuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta veya lisans anahtarınız boş olamaz!.
        /// </summary>
        internal static string epostaVeyaLisansAnahtariBos {
            get {
                return ResourceManager.GetString("epostaVeyaLisansAnahtariBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kullanıcı Kaydı.
        /// </summary>
        internal static string epostaYeniKullaniciKaydi {
            get {
                return ResourceManager.GetString("epostaYeniKullaniciKaydi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye {
            get {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_off {
            get {
                object obj = ResourceManager.GetObject("eye-off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string FrmGirisYapBaslik {
            get {
                return ResourceManager.GetString("FrmGirisYapBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güçlü Şifre Oluşturucu.
        /// </summary>
        internal static string FrmGucluSifreOlustur {
            get {
                return ResourceManager.GetString("FrmGucluSifreOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtları Göster.
        /// </summary>
        internal static string FrmKayitlariGoster {
            get {
                return ResourceManager.GetString("FrmKayitlariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans Anahtarı Gir.
        /// </summary>
        internal static string FrmLisans {
            get {
                return ResourceManager.GetString("FrmLisans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili Düzenle.
        /// </summary>
        internal static string FrmProfil {
            get {
                return ResourceManager.GetString("FrmProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Servis Formu.
        /// </summary>
        internal static string FrmTeknikServisFormu {
            get {
                return ResourceManager.GetString("FrmTeknikServisFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçici kullanıcı adı ve şifreniz e-posta adresinize gönderilmiştir!.
        /// </summary>
        internal static string geciciKullaniciAdiSifreGonderildi {
            get {
                return ResourceManager.GetString("geciciKullaniciAdiSifreGonderildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçici şifreniz e-posta adresinize gönderilmiştir!.
        /// </summary>
        internal static string geciciSifreGonderildi {
            get {
                return ResourceManager.GetString("geciciSifreGonderildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aksesuarlar.
        /// </summary>
        internal static string GrpBoxAksesuarlar {
            get {
                return ResourceManager.GetString("GrpBoxAksesuarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Yap.
        /// </summary>
        internal static string GrpBoxArama {
            get {
                return ResourceManager.GetString("GrpBoxArama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ek Bilgiler.
        /// </summary>
        internal static string GrpBoxEkBilgiler {
            get {
                return ResourceManager.GetString("GrpBoxEkBilgiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Bilgileri.
        /// </summary>
        internal static string GrpBoxMusteriBilgileri {
            get {
                return ResourceManager.GetString("GrpBoxMusteriBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Bilgileri.
        /// </summary>
        internal static string GrpBoxUrunBilgileri {
            get {
                return ResourceManager.GetString("GrpBoxUrunBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla güncellendi!.
        /// </summary>
        internal static string guncellendi {
            get {
                return ResourceManager.GetString("guncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string Hata {
            get {
                return ResourceManager.GetString("Hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla kaydedildi!.
        /// </summary>
        internal static string kaydedildi {
            get {
                return ResourceManager.GetString("kaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı bir kullanıcı zaten var!.
        /// </summary>
        internal static string kayitliKullaniciVar {
            get {
                return ResourceManager.GetString("kayitliKullaniciVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı kullanıcı yok lütfen yeni bir kullanıcı oluşturun!.
        /// </summary>
        internal static string kayitliKullaniciYok {
            get {
                return ResourceManager.GetString("kayitliKullaniciYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınız boş olamaz!.
        /// </summary>
        internal static string kullaniciAdiBosOlamaz {
            get {
                return ResourceManager.GetString("kullaniciAdiBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifreniz boş olamaz!.
        /// </summary>
        internal static string kullaniciAdiveSifreBos {
            get {
                return ResourceManager.GetString("kullaniciAdiveSifreBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifreniz yanlış!.
        /// </summary>
        internal static string kullaniciAdiveSifreYanlis {
            get {
                return ResourceManager.GetString("kullaniciAdiveSifreYanlis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız:.
        /// </summary>
        internal static string LblAdiniz {
            get {
                return ResourceManager.GetString("LblAdiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arızanın Tanımı.
        /// </summary>
        internal static string LblArizaTanimi {
            get {
                return ResourceManager.GetString("LblArizaTanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        internal static string LblEposta {
            get {
                return ResourceManager.GetString("LblEposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresiniz:.
        /// </summary>
        internal static string LblEpostaniz {
            get {
                return ResourceManager.GetString("LblEpostaniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form No:.
        /// </summary>
        internal static string LblFormNo {
            get {
                return ResourceManager.GetString("LblFormNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güçlü Şifreniz:.
        /// </summary>
        internal static string lblGucluSifreniz {
            get {
                return ResourceManager.GetString("lblGucluSifreniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string lblKullaniciAdi {
            get {
                return ResourceManager.GetString("lblKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınız:.
        /// </summary>
        internal static string LblKullaniciAdiniz {
            get {
                return ResourceManager.GetString("LblKullaniciAdiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans Anahtarınız:.
        /// </summary>
        internal static string LblLisansAnahtari {
            get {
                return ResourceManager.GetString("LblLisansAnahtari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta Adresiniz:.
        /// </summary>
        internal static string LblLisansEposta {
            get {
                return ResourceManager.GetString("LblLisansEposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Adı:.
        /// </summary>
        internal static string LblMusteriAdi {
            get {
                return ResourceManager.GetString("LblMusteriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Kodu.
        /// </summary>
        internal static string LblMusteriQrKodu {
            get {
                return ResourceManager.GetString("LblMusteriQrKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string LblSifre {
            get {
                return ResourceManager.GetString("LblSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz:.
        /// </summary>
        internal static string LblSifreniz {
            get {
                return ResourceManager.GetString("LblSifreniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi onaylayın:.
        /// </summary>
        internal static string LblSifreniziOnaylayın {
            get {
                return ResourceManager.GetString("LblSifreniziOnaylayın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Uzunluğu:.
        /// </summary>
        internal static string lblSifreUzunlugu {
            get {
                return ResourceManager.GetString("lblSifreUzunlugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız:.
        /// </summary>
        internal static string LblSoyadiniz {
            get {
                return ResourceManager.GetString("LblSoyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string LblTelefon {
            get {
                return ResourceManager.GetString("LblTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücret.
        /// </summary>
        internal static string LblUcret {
            get {
                return ResourceManager.GetString("LblUcret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Durumu.
        /// </summary>
        internal static string LblUrunDurumu {
            get {
                return ResourceManager.GetString("LblUrunDurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Modeli.
        /// </summary>
        internal static string LblUrunModeli {
            get {
                return ResourceManager.GetString("LblUrunModeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Numarası.
        /// </summary>
        internal static string LblUrunTakipNo {
            get {
                return ResourceManager.GetString("LblUrunTakipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum?.
        /// </summary>
        internal static string LinkLblSifremiUnuttum {
            get {
                return ResourceManager.GetString("LinkLblSifremiUnuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu programı satın aldığınız için teşekkür ederiz!.
        /// </summary>
        internal static string lisansBasarili {
            get {
                return ResourceManager.GetString("lisansBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans anahtarı doğru değil lütfen tekrar deneyin!.
        /// </summary>
        internal static string lisansTekrarDene {
            get {
                return ResourceManager.GetString("lisansTekrarDene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metin kutuları boş olamaz!.
        /// </summary>
        internal static string metinKutulariBos {
            get {
                return ResourceManager.GetString("metinKutulariBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir müşteri seçin!.
        /// </summary>
        internal static string musteriSec {
            get {
                return ResourceManager.GetString("musteriSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiliniz başarıyla güncellendi!.
        /// </summary>
        internal static string profilBasariylaGuncellendi {
            get {
                return ResourceManager.GetString("profilBasariylaGuncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form No&apos;suna Göre Ara.
        /// </summary>
        internal static string RadioBttnFormNoyaGoreAra {
            get {
                return ResourceManager.GetString("RadioBttnFormNoyaGoreAra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Adına Göre Ara.
        /// </summary>
        internal static string RadioBttnMusteriIsmineGoreAra {
            get {
                return ResourceManager.GetString("RadioBttnMusteriIsmineGoreAra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Dosyaları(*.bmp;*.png;*.jpg)|*.bmp;*.png;*.jpg|SMF Biçimi(*.smf)|*.smf.
        /// </summary>
        internal static string resimSecFilter {
            get {
                return ResourceManager.GetString("resimSecFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil resminizi seçin.
        /// </summary>
        internal static string resimSecTitle {
            get {
                return ResourceManager.GetString("resimSecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kaydı düzenliyorsunuz!.
        /// </summary>
        internal static string secilenKaydiDuzenliyorsun {
            get {
                return ResourceManager.GetString("secilenKaydiDuzenliyorsun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kayıt silindi!.
        /// </summary>
        internal static string secilenKayitSilindi {
            get {
                return ResourceManager.GetString("secilenKayitSilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen şifreler aynı değil!.
        /// </summary>
        internal static string sifreAyniDegil {
            get {
                return ResourceManager.GetString("sifreAyniDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla silindi!.
        /// </summary>
        internal static string silindi {
            get {
                return ResourceManager.GetString("silindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araçlar.
        /// </summary>
        internal static string TlStrpMenuItemAraclar {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güçlü Şifre Oluşturucu.
        /// </summary>
        internal static string TlStrpMenuItemAraclarGucluSifreOlustur {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclarGucluSifreOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string TlStrpMenuItemAraclarGuncelle {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclarGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string TlStrpMenuItemAraclarKaydet {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclarKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtları Göster.
        /// </summary>
        internal static string TlStrpMenuItemAraclarKayitlariGoster {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclarKayitlariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string TlStrpMenuItemAraclarSil {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclarSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string TlStrpMenuItemAraclarTemizle {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclarTemizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kayıt.
        /// </summary>
        internal static string TlStrpMenuItemAraclarYeniKayit {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAraclarYeniKayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string TlStrpMenuItemAyarlar {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAyarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string TlStrpMenuItemAyarlarDil {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAyarlarDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string TlStrpMenuItemAyarlarTema {
            get {
                return ResourceManager.GetString("TlStrpMenuItemAyarlarTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        internal static string TlStrpMenuItemDilIngilizce {
            get {
                return ResourceManager.GetString("TlStrpMenuItemDilIngilizce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string TlStrpMenuItemDilTurkce {
            get {
                return ResourceManager.GetString("TlStrpMenuItemDilTurkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yardım.
        /// </summary>
        internal static string TlStrpMenuItemYardim {
            get {
                return ResourceManager.GetString("TlStrpMenuItemYardim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        internal static string TlStrpMenuItemYardimHakkinda {
            get {
                return ResourceManager.GetString("TlStrpMenuItemYardimHakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans Anahtarı.
        /// </summary>
        internal static string TlStrpMenuItemYardimLisansAnahtari {
            get {
                return ResourceManager.GetString("TlStrpMenuItemYardimLisansAnahtari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string varsayilanAciklama {
            get {
                return ResourceManager.GetString("varsayilanAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap varsayilanProfilResmi {
            get {
                object obj = ResourceManager.GetObject("varsayilanProfilResmi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
